zup-api:
  image: timcr/zup-api
  env_file:
    - ../config/api.env
  volumes:
    - /opt/zup/uploads:/usr/src/app/public/uploads
    - /opt/zup/logs/api:/usr/src/app/log
    - /opt/zup/config:/usr/src/app/config/permissions
    - /opt/zup/shared_images:/usr/src/app/public/shared_images
  ports:
    - 8282:80
  links:
   - redis
   - postgres

postgres:
  image: ntxcode/postgresql:9.4
  env_file:
    - ../config/postgres.env
  volumes:
    - /opt/zup/postgres-data:/var/lib/postgresql/data
#  ports:
#    - 5432:5432

redis:
  image: redis:2.8

web:
  image: timcr/zup-web
  env_file:
    - ../config/web.env
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /opt/zup/logs/nginx:/var/log/nginx
  ports:
    - 80:80
